version: '3.3'
services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    expose:
      - 27017
    volumes:
      - ./dummy-data:/docker-entrypoint-initdb.d/
    networks:
      - db-network
  # db management sceen used for debugging etc
  # admin:
  #   image: mrvautin/adminmongo:latest
  #   environment:
  #     CONN_NAME: admin-connection
  #     DB_HOST: db
  #     DB_PORT: 27017
  #     HOST: 0.0.0.0
  #   ports:
  #     - 1234:1234
  #   networks:
  #     - db-network
  server:
    build: ./packages/backend/
    restart: always
    expose:
      - 3000
    networks:
      - db-network
      - app-network
    command: npm start
  app:
    build: ./packages/client/
    restart: always
    networks:
      - app-network
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  my-db:
networks:
  db-network:
  app-network:
