version: '3.3'
services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    expose:
      - 27017
    # For devolpment
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - db-network
  admin:
    image: mrvautin/adminmongo:latest
    environment:
      CONN_NAME: admin-connection
      DB_HOST: db
      DB_PORT: 27017
      PASSWORD: ${ADMIN_PASSWORD}
      HOST: 0.0.0.0
    ports:
      - 1234:1234
    networks:
      - db-network
  app:
    build: .
    restart: always
    expose:
      - 3000
    links:
      - db
    networks:
      - db-network
    command: npm start
volumes:
  my-db:
networks:
  db-network:
